In [20]:
import numpy as np

M = np.random.rand(3, 4) 
N = np.random.rand(3, 4) 
O = M + N
# subM = M[0:2, 1:3]

MTp = np.transpose(M)

In [23]:
print(M)
print(N)
# print(O)
# print(MTp)
# print(subM)

try:
    pass
    # print(N + MTp) # undefined operation if matrices aren't same size, as usual
except ValueError:
    print('hello') 

# print(np.matmul(M.T, N))
print(M.T @ N) # same as above
# print((M.T @ N) == np.matmul(M.T, N))

[[0.82125587 0.57340038 0.55893923 0.68432404]
 [0.31776909 0.39586006 0.0265377  0.67824145]
 [0.05433501 0.44737827 0.98769343 0.66150622]]
[[0.16597713 0.25454045 0.83332911 0.39991614]
 [0.23174516 0.35879403 0.54922063 0.20301919]
 [0.38836298 0.01535092 0.94520788 0.66589493]]
[[0.23105285 0.32389058 0.91025964 0.42912811]
 [0.36065516 0.29485348 1.11811121 0.60758618]
 [0.48250468 0.16695621 1.413931   0.88661654]
 [0.52766584 0.42769185 1.56803222 0.8518619 ]]
[[0.23105285 0.32389058 0.91025964 0.42912811]
 [0.36065516 0.29485348 1.11811121 0.60758618]
 [0.48250468 0.16695621 1.413931   0.88661654]
 [0.52766584 0.42769185 1.56803222 0.8518619 ]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [25]:
X = np.random.rand(2, 2) 
Y = np.random.rand(2, 2)

print(A * B)
print(A.T @ B)
# print(A)
# print(B)

[[0.38777425 0.19371601]
 [0.00581648 0.1863211 ]]
[[0.39359072 0.26437011]
 [0.38123881 0.38003711]]
[[0.76959155 0.71888012]
 [0.15870269 0.51886667]]
[[0.5038702  0.26946914]
 [0.03665014 0.35909244]]


In [43]:
A = np.random.rand(4, 4)
b = np.random.rand(4, 1)

x = np.linalg.solve(A, b)
# print(A)
# print(b)
# print(A @ x)
print(A @ x - b)

np.linalg.matrix_rank(A)
np.linalg.qr(A, mode='complete')
# np.linalg.qr(A, mode='reduced')

[[0.00000000e+00]
 [1.38777878e-17]
 [0.00000000e+00]
 [0.00000000e+00]]


(array([[-0.05734538,  0.35972666,  0.91894321,  0.15116753],
        [-0.85763895, -0.48982579,  0.14707642, -0.05380191],
        [-0.33054327,  0.61254203, -0.14472191, -0.7032702 ],
        [-0.38975387,  0.50543019, -0.33610636,  0.69257834]]),
 array([[-1.04394995, -0.88488962, -1.34979034, -0.53064852],
        [ 0.        ,  1.10452962,  0.85271689,  0.58449906],
        [ 0.        ,  0.        ,  0.51432315,  0.20915764],
        [ 0.        ,  0.        ,  0.        ,  0.70567007]]))

In [46]:
C = np.random.rand(3, 2)
Q, R = np.linalg.qr(C, mode = 'complete')
# print(Q)
# print(R)
# print(Q @ R - C)

Q, R = np.linalg.qr(C, mode = 'reduced')
# print(Q)
# print(R)
# print(Q @ R - C)

In [57]:
D = np.random.rand(4, 4)
U, E, Vh = np.linalg.svd(D, full_matrices = True)
print((U @ np.diag(E)) @ Vh - D)
print(E)

[[-2.22044605e-16 -1.11022302e-16 -1.11022302e-16 -2.22044605e-16]
 [-5.55111512e-17  5.55111512e-17 -3.33066907e-16  1.11022302e-16]
 [-1.11022302e-16  5.55111512e-17 -3.33066907e-16  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -5.55111512e-17  0.00000000e+00]]
[2.00570294 0.95391932 0.36298355 0.03552021]


In [82]:
F = np.random.rand(4, 4)
w, v = np.linalg.eig(F)
print(w)
print(v)

print(F @ v[:, 0] - w[0] * v[:, 0])

[ 1.60170612 -1.00998649  0.06832264 -0.09158496]
[[ 0.349849    0.45945986  0.77509072  0.69302617]
 [ 0.41669484  0.26286477 -0.43236257 -0.71441903]
 [ 0.63307569 -0.77632292  0.14999533  0.08049999]
 [ 0.55062351  0.34223014 -0.43565856 -0.05329101]]
[-5.55111512e-16 -9.99200722e-16 -8.88178420e-16 -9.99200722e-16]


In [84]:
G = np.random.rand(2, 2)
GI = np.linalg.inv(G)
print(G @ GI)
print(GI @ G)

[[1.00000000e+00 2.22044605e-16]
 [0.00000000e+00 1.00000000e+00]]
[[1.00000000e+00 8.88178420e-16]
 [2.22044605e-16 1.00000000e+00]]


In [91]:
H = np.array([1, 1, 0, 1])
H = np.reshape(H, (2, 2))
# print(H)
# print(np.linalg.matrix_power(H, 2))
# print(np.linalg.matrix_power(H, 3))
# print(np.linalg.matrix_power(H, 4))
print(np.linalg.det(H), np.trace(H))
J = np.random.rand(2, 2)
print(J)
print(np.linalg.det(J), np.trace(J))
print(J[0][0] * J[1][1] - J[0][1] * J[1][0], J[0][0] + J[1][1] )


1.0 2
[[0.47899665 0.97847999]
 [0.39103271 0.91078604]]
0.0536457775075676 1.3897826857565343
0.053645777507567605 1.3897826857565343


In [98]:
v = np.array([1 + 2j, 1 + 3j, 1 + 4j])
print(np.imag(v))
print(np.real(v))
print(np.linalg.norm(v))
print(np.sqrt(np.inner(v,np.conj(v))))

[2. 3. 4.]
[1. 1. 1.]
5.656854249492381
(5.656854249492381+0j)


In [99]:
a = np.arange(4)
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])