In [52]:
import numpy as np
from numpy.random import default_rng
rng = default_rng() 

In [23]:
sample = rng.normal(0.0, 1.0, 8)
print(sample)

[ 0.975014   -1.34098077  0.2964399  -0.43531402  0.68361286 -0.29457563
 -0.13074232 -0.00201476]


In [13]:
sample = rng.binomial(50, 0.2, 8)
print(sample)

[13  8 13  7  9  9  6 10]


In [22]:
sample = rng.hypergeometric(50, 17, 8, 8)
print(sample)

[7 6 5 5 4 6 6 4]


In [37]:
sample = rng.normal(0.0, 1.0, 1000)
print(sum(sample) / 1000)

-0.017684860327970495


In [41]:
import scipy as sp
from scipy.stats import binom

sample = rng.binomial(50, 0.2, 8)
print(sample)

# binom.pmf(11, 50, 0.2) #  0.1271082 from R
# binom.cdf(11, 50, 0.2) #  0.7106676 from R

print(binom.mean(50, 0.2), binom.median(50, 0.2), binom.var(50, 0.2), binom.std(50, 0.2))

[ 7 10 10  8 10 10  9  8]
10.0 10.0 8.0 2.8284271247461903


In [49]:
from scipy.stats import norm

sample = rng.normal(0, 1, 1000)
# print(sample)

print(norm.cdf(50, 35, 15)) # 0.8413447
print(norm.cdf(1, 0, 1))
norm.ppf(0.975, 0, 1)


0.8413447460685429
0.8413447460685429


1.959963984540054

In [181]:
n = 30
sample = rng.normal(0, 1, n)
mu0 = 0.1
mu1 = 0.01
xbar = np.mean(sample)
S = np.std(sample, ddof=1) # unbiased sample stdev
S2 = np.var(sample, ddof=1) # unbiased sample variance
# print(S, S2)
# print(xbar)
T = abs((n ** 0.5) * (xbar - mu0)/S)
print(T)

from scipy.stats import t
2*t.cdf(-T, df=n-1)


1.3040438043049243


0.20247495477829391

In [182]:
from scipy.stats import ttest_1samp
sample = rng.normal(0, 1, n)
print(sp.stats.ttest_1samp(sample, popmean = 0.0, alternative = 'two-sided'))
print(sp.stats.ttest_1samp(sample, popmean = 10, alternative = 'two-sided'))
print(sp.stats.ttest_1samp(sample, popmean = 0.1, alternative = 'two-sided'))

Ttest_1sampResult(statistic=0.4255343428855565, pvalue=0.673588605825653)
Ttest_1sampResult(statistic=-58.17698039912953, pvalue=1.3867247890115268e-31)
Ttest_1sampResult(statistic=-0.1604908045345944, pvalue=0.8736072076791018)
